# ttk.tcl -- generated by Omarchy from the active theme's colors.toml.
#
# DO NOT EDIT. This file is rewritten on every `omarchy theme set`.
# Source: themed/ttk.tcl.tpl in tk-omarchy-theme
#
# Registers a ttk theme named "omarchy" built entirely from ttk::style
# statements -- no image elements, so the whole thing is a text substitution
# away from any palette. Sourcing it also repaints the classic (non-ttk)
# widgets, which ttk styling never reaches.
#
# Use it from a Tk app:
#     source $::env(XDG_STATE_HOME)/omarchy/current/theme/ttk.tcl
# or point gitk's "Theme definition file" preference at this path.

package require Tk 8.6-

namespace eval ttk::theme::omarchy {
    variable version 1.0
    variable colors

    # The live Omarchy palette, so an application can colour its own canvases
    # and text tags from the same source: ttk::theme::omarchy::color accent
    array set colors {
        mode        light
        bg          #eff1f5
        fg          #4c4f69
        accent      #1e66f5
        muted       #acb0be
        selectbg    #ccd0da
        selectfg    #4c4f69

        field       #e5e7ed
        raised      #dfe1e7
        hover       #d5d7df
        pressed     #cbcdd6
        border      #c1c4ce
        trough      #dbdee4
        disabledfg  #9ea0af

        red         #d20f39
        green       #40a02b
        yellow      #df8e1d
        blue        #1e66f5
        magenta     #ea76cb
        cyan        #179299
        orange      #d84e2b
        bright_fg   #4c4f69
    }

    proc color {name} {
        variable colors
        if {![info exists colors($name)]} { return "" }
        return $colors($name)
    }

    proc is_dark {} {
        variable colors
        return [expr {$colors(mode) eq "dark"}]
    }

    # tk_setPalette and the option database are the only levers that reach
    # classic widgets (text, listbox, canvas, menu, the Tk dialogs). ttk never
    # consults them, and they never reach a ttk widget -- the two halves are
    # disjoint, so both have to run.
    # --- perceptual colour helpers -------------------------------------
    # Internal. sRGB -> CIELAB, so "are these two colours tellable apart" is a
    # number rather than an opinion. Euclidean distance in RGB is not that
    # number: it rates #549e6a against #459451 as far apart when they are the
    # same green to the eye.
    proc Lab {hex} {
        scan [string range $hex 1 end] %2x%2x%2x r g b
        set lin {}
        foreach c [list $r $g $b] {
            set v [expr {$c / 255.0}]
            lappend lin [expr {$v <= 0.04045 ? $v / 12.92 : pow(($v + 0.055) / 1.055, 2.4)}]
        }
        lassign $lin r g b
        set x [expr {(0.4124 * $r + 0.3576 * $g + 0.1805 * $b) / 0.95047}]
        set y [expr {0.2126 * $r + 0.7152 * $g + 0.0722 * $b}]
        set z [expr {(0.0193 * $r + 0.1192 * $g + 0.9505 * $b) / 1.08883}]
        set f {}
        foreach t [list $x $y $z] {
            lappend f [expr {$t > 0.008856 ? pow($t, 1.0/3.0) : 7.787 * $t + 16.0/116.0}]
        }
        lassign $f fx fy fz
        return [list [expr {116 * $fy - 16}] [expr {500 * ($fx - $fy)}] [expr {200 * ($fy - $fz)}]]
    }

    proc DeltaE {a b} {
        lassign [Lab $a] l1 a1 b1
        lassign [Lab $b] l2 a2 b2
        return [expr {sqrt(pow($l1-$l2,2) + pow($a1-$a2,2) + pow($b1-$b2,2))}]
    }

    proc Luminance {hex} {
        scan [string range $hex 1 end] %2x%2x%2x r g b
        set out 0.0
        foreach c [list $r $g $b] w {0.2126 0.7152 0.0722} {
            set v [expr {$c / 255.0}]
            set v [expr {$v <= 0.03928 ? $v / 12.92 : pow(($v + 0.055) / 1.055, 2.4)}]
            set out [expr {$out + $w * $v}]
        }
        return $out
    }

    # WCAG contrast ratio, 1.0 (identical) to 21.0 (black on white).
    proc Contrast {a b} {
        set la [Luminance $a]
        set lb [Luminance $b]
        if {$la < $lb} { lassign [list $lb $la] la lb }
        return [expr {($la + 0.05) / ($lb + 0.05)}]
    }

    # Pick $n palette colours that are readable on the background and as far
    # apart from each other as this theme allows.
    #
    # Do NOT hand-map meanings onto red/green/yellow/blue: those are terminal
    # palette slots, not a categorical scale, and themes collapse them. On
    # osaka-jade, green/yellow/blue sit within deltaE 21 of one another and
    # blue is byte-identical to accent -- five status rows named that way give
    # you three indistinguishable greens. matte-black and retro-82 are worse:
    # those five names land on deltaE 0.0, one colour wearing five hats.
    #
    # Selection is exhaustive, not greedy. The pool is small by construction
    # (eight or nine candidates), so every combination can be scored and the
    # best min-pairwise-distance taken. Greedy furthest-point was tried first
    # and lost to plain naming on three themes: it is seeded with one colour
    # and never recovers from a bad seed. Because the naming a consumer would
    # have written by hand is itself one of the combinations considered, the
    # result can never be worse than it -- test/hues.sh asserts that.
    #
    # Returns a list of $n hex colours. If the theme cannot supply $n readable
    # ones the contrast floor is relaxed rather than returning a short list.
    proc distinct_hues {n {pool {}}} {
        variable colors
        if {$n <= 0} { return {} }
        # fg and bright_fg are deliberately last: they are text colours, and a
        # theme with high-contrast text will otherwise see them crowd out the
        # actual hues.
        if {$pool eq {}} {
            set pool {accent red green yellow blue magenta cyan orange fg bright_fg}
        }

        set readable {}
        set rest {}
        foreach key $pool {
            set hex [color $key]
            if {![regexp {^#[0-9a-fA-F]{6}$} $hex]} { continue }
            set dup 0
            foreach seen [concat $readable $rest] {
                if {[string equal -nocase $seen $hex]} { set dup 1; break }
            }
            if {$dup} { continue }
            if {[Contrast $hex $colors(bg)] >= 3.0} {
                lappend readable $hex
            } else {
                lappend rest $hex
            }
        }
        while {[llength $readable] < $n && [llength $rest] > 0} {
            lappend readable [lindex $rest 0]
            set rest [lrange $rest 1 end]
        }
        if {[llength $readable] <= $n} { return $readable }

        set best {}
        set best_score -1
        foreach combo [Combinations $readable $n] {
            set score [spread $combo]
            if {$score > $best_score} { set best_score $score; set best $combo }
        }
        return $best
    }

    # Internal. All $n-element subsets of $items, order-insensitive.
    proc Combinations {items n} {
        if {$n == 0} { return [list {}] }
        set out {}
        set len [llength $items]
        for {set i 0} {$i <= $len - $n} {incr i} {
            set head [lindex $items $i]
            foreach tail [Combinations [lrange $items [expr {$i + 1}] end] [expr {$n - 1}]] {
                lappend out [linsert $tail 0 $head]
            }
        }
        return $out
    }

    # WCAG contrast ratio between two colours, 1.0 to 21.0. Public: a consumer
    # choosing text to sit on one of its own colours needs the same number this
    # theme uses internally. 4.5 is the floor for body text, 3.0 for large.
    proc contrast {a b} { return [Contrast $a $b] }

    # Smallest pairwise deltaE in a list of colours. Below about 25 is hard to
    # tell apart; use it to decide whether to fall back to glyphs or weight.
    proc spread {hexes} {
        set worst 1e9
        set n [llength $hexes]
        for {set i 0} {$i < $n} {incr i} {
            for {set j [expr {$i + 1}]} {$j < $n} {incr j} {
                set d [DeltaE [lindex $hexes $i] [lindex $hexes $j]]
                if {$d < $worst} { set worst $d }
            }
        }
        return [expr {$n < 2 ? 0.0 : $worst}]
    }

    # Walk the widget tree applying the field colour to the classic text
    # classes. Only touches widgets whose colour we already own -- a widget the
    # application has coloured itself keeps its colour.
    proc retint {w} {
        variable colors
        switch -- [winfo class $w] {
            Text - Listbox - Entry - Spinbox {
                catch {$w configure -background $colors(field) -foreground $colors(fg)}
                catch {$w configure -insertbackground $colors(fg)}
                catch {$w configure -selectbackground $colors(selectbg) \
                                    -selectforeground $colors(selectfg)}
            }
            Menu {
                catch {$w configure -background $colors(bg) -foreground $colors(fg) \
                                    -activebackground $colors(selectbg) \
                                    -activeforeground $colors(selectfg) \
                                    -selectcolor $colors(accent)}
            }
            Scrollbar - Scale {
                catch {$w configure -background $colors(border) \
                                    -activebackground $colors(disabledfg) \
                                    -troughcolor $colors(bg)}
            }
        }
        foreach child [winfo children $w] { retint $child }
    }

    proc repaint {} {
        variable colors

        tk_setPalette \
            background       $colors(bg) \
            foreground       $colors(fg) \
            activeBackground $colors(hover) \
            activeForeground $colors(fg) \
            disabledForeground $colors(disabledfg) \
            highlightBackground $colors(bg) \
            highlightColor   $colors(accent) \
            insertBackground $colors(fg) \
            selectBackground $colors(selectbg) \
            selectForeground $colors(selectfg) \
            troughColor      $colors(trough)

        # tk_setPalette paints every widget class the same; the text-entry
        # classes want the recessed field colour instead. These need
        # userDefault priority: tk_setPalette's own `*background` entry beats
        # a class-specific `*Text.background` at widgetDefault AND at
        # startupFile -- measured, not assumed -- and userDefault is the first
        # level that takes. See test/option-priority.tcl.
        foreach class {Text Listbox Entry Spinbox} {
            option add *$class.background $colors(field) userDefault
            option add *$class.foreground $colors(fg) userDefault
            option add *$class.selectBackground $colors(selectbg) userDefault
            option add *$class.selectForeground $colors(selectfg) userDefault
            option add *$class.inactiveSelectBackground $colors(trough) userDefault
            option add *$class.highlightBackground $colors(bg) userDefault
            option add *$class.highlightColor $colors(accent) userDefault
        }
        option add *Text.insertBackground $colors(fg) userDefault

        # The classic scrollbar and scale draw their thumb with -background,
        # which tk_setPalette has just set to the window background -- so the
        # thumb becomes invisible against its own trough. ttk::scrollbar is
        # unaffected, but plenty of code still uses the classic one.
        # Thumb and trough must be far apart, not adjacent steps: `raised` and
        # `trough` differ by 2% and rendered as one flat bar. These are the same
        # two values the ttk scrollbar above uses.
        foreach class {Scrollbar Scale} {
            option add *$class.background $colors(border) userDefault
            option add *$class.activeBackground $colors(disabledfg) userDefault
            option add *$class.troughColor $colors(bg) userDefault
            option add *$class.highlightThickness 0 userDefault
            option add *$class.borderWidth 0 userDefault
        }
        option add *Scrollbar.elementBorderWidth 1 userDefault
        option add *Scrollbar.width 12 userDefault
        option add *Scale.sliderRelief flat userDefault
        option add *Menu.activeBackground $colors(selectbg) userDefault
        option add *Menu.activeForeground $colors(selectfg) userDefault
        option add *Menu.selectColor $colors(accent) userDefault
        option add *Menu.borderWidth 1 userDefault
        option add *Menu.relief solid userDefault

        # tk_setPalette reconfigures widgets that already exist, so on a live
        # re-source it has just repainted every text pane with the plain
        # background. The option-database entries above only reach widgets
        # created from here on, so the existing ones need the field colour put
        # back by hand.
        retint .

        # The combobox dropdown is a classic listbox inside a ttk widget.
        option add *TCombobox*Listbox.background $colors(field) userDefault
        option add *TCombobox*Listbox.foreground $colors(fg) userDefault
        option add *TCombobox*Listbox.selectBackground $colors(selectbg) userDefault
        option add *TCombobox*Listbox.selectForeground $colors(selectfg) userDefault
    }
}

# Creating the theme and configuring it are deliberately separate. A running
# application re-sources this file after `omarchy theme set` to pick up the new
# palette, and `theme create` would fail the second time -- while the settings
# block is re-appliable, so the live widgets actually change colour. Doing it
# in one `theme create -settings` call would make re-sourcing a silent no-op.
if {[lsearch -exact [ttk::style theme names] omarchy] < 0} {
    ttk::style theme create omarchy -parent clam
}

ttk::style theme settings omarchy {
    ttk::style configure . \
        -background      #eff1f5 \
        -foreground      #4c4f69 \
        -troughcolor     #dbdee4 \
        -fieldbackground #e5e7ed \
        -bordercolor     #c1c4ce \
        -darkcolor       #dfe1e7 \
        -lightcolor      #dfe1e7 \
        -focuscolor      #1e66f5 \
        -selectbackground #ccd0da \
        -selectforeground #4c4f69 \
        -insertcolor     #4c4f69 \
        -insertwidth     1 \
        -borderwidth     1 \
        -relief          flat \
        -font            TkDefaultFont

    ttk::style map . \
        -background [list disabled #eff1f5 active #d5d7df] \
        -foreground [list disabled #9ea0af] \
        -selectbackground [list !focus #dbdee4] \
        -selectforeground [list !focus #4c4f69]

    # ---- buttons -------------------------------------------------------
    ttk::style configure TButton \
        -anchor center -width -10 -padding {10 5} -relief flat \
        -background #dfe1e7
    ttk::style map TButton \
        -background [list \
            disabled #e8ebef \
            pressed  #cbcdd6 \
            active   #d5d7df] \
        -bordercolor [list focus #1e66f5] \
        -lightcolor [list pressed #cbcdd6] \
        -darkcolor  [list pressed #cbcdd6]

    # An accent button for the one action a dialog actually wants.
    ttk::style configure Accent.TButton \
        -background #1e66f5 -foreground #eff1f5
    ttk::style map Accent.TButton \
        -background [list \
            disabled #dfe1e7 \
            pressed  #5289f5 \
            active   #2563e0] \
        -foreground [list disabled #9ea0af] \
        -lightcolor [list pressed #5289f5] \
        -darkcolor  [list pressed #5289f5]

    ttk::style configure Toolbutton -anchor center -padding 4 -relief flat \
        -background #eff1f5
    ttk::style map Toolbutton \
        -background [list \
            selected #ccd0da \
            pressed  #cbcdd6 \
            active   #d5d7df]

    ttk::style configure TMenubutton \
        -padding {10 5 6 5} -relief flat \
        -background #dfe1e7 \
        -arrowcolor #4c4f69
    ttk::style map TMenubutton \
        -background [list \
            disabled #e8ebef \
            active   #d5d7df] \
        -arrowcolor [list disabled #9ea0af]

    # ---- indicators ----------------------------------------------------
    ttk::style configure TCheckbutton \
        -padding 4 -indicatorbackground #e5e7ed \
        -indicatorforeground #eff1f5 \
        -indicatormargin {0 0 6 0}
    ttk::style map TCheckbutton \
        -background [list active #e2e4ea] \
        -indicatorbackground [list \
            {alternate !disabled} #1e66f5 \
            {selected !disabled} #1e66f5 \
            {pressed !disabled} #cbcdd6 \
            disabled #e8ebef] \
        -indicatorforeground [list \
            {selected !disabled} #eff1f5 \
            disabled #9ea0af]

    ttk::style configure TRadiobutton \
        -padding 4 -indicatorbackground #e5e7ed \
        -indicatorforeground #eff1f5 \
        -indicatormargin {0 0 6 0}
    ttk::style map TRadiobutton \
        -background [list active #e2e4ea] \
        -indicatorbackground [list \
            {selected !disabled} #1e66f5 \
            {pressed !disabled} #cbcdd6 \
            disabled #e8ebef] \
        -indicatorforeground [list \
            {selected !disabled} #eff1f5 \
            disabled #9ea0af]

    # ---- text entry ----------------------------------------------------
    ttk::style configure TEntry \
        -padding {8 5} -insertcolor #4c4f69 \
        -fieldbackground #e5e7ed \
        -bordercolor #c1c4ce \
        -lightcolor #e5e7ed \
        -darkcolor #e5e7ed
    ttk::style map TEntry \
        -fieldbackground [list disabled #eff1f5 readonly #eff1f5] \
        -bordercolor [list focus #1e66f5 invalid #d20f39] \
        -lightcolor [list focus #1e66f5] \
        -foreground [list disabled #9ea0af]

    ttk::style configure TSpinbox \
        -padding {8 5 0 5} -arrowsize 12 \
        -arrowcolor #4c4f69 \
        -fieldbackground #e5e7ed \
        -bordercolor #c1c4ce \
        -lightcolor #e5e7ed \
        -darkcolor #e5e7ed
    ttk::style map TSpinbox \
        -fieldbackground [list disabled #eff1f5 readonly #eff1f5] \
        -bordercolor [list focus #1e66f5] \
        -lightcolor [list focus #1e66f5] \
        -arrowcolor [list disabled #9ea0af]

    ttk::style configure TCombobox \
        -padding {8 5 0 5} -arrowsize 12 \
        -arrowcolor #4c4f69 \
        -fieldbackground #e5e7ed \
        -bordercolor #c1c4ce \
        -lightcolor #e5e7ed \
        -darkcolor #e5e7ed
    ttk::style map TCombobox \
        -fieldbackground [list \
            disabled #eff1f5 \
            readonly #dfe1e7] \
        -bordercolor [list focus #1e66f5] \
        -lightcolor [list focus #1e66f5] \
        -foreground [list disabled #9ea0af] \
        -arrowcolor [list disabled #9ea0af]

    # ---- containers ----------------------------------------------------
    ttk::style configure TLabelframe \
        -background #eff1f5 \
        -bordercolor #c1c4ce \
        -lightcolor #c1c4ce \
        -darkcolor #c1c4ce \
        -relief solid -borderwidth 1
    ttk::style configure TLabelframe.Label \
        -background #eff1f5 -foreground #4c4f69

    ttk::style configure Card.TFrame \
        -background #e5e7ed \
        -bordercolor #c1c4ce \
        -relief solid -borderwidth 1

    ttk::style configure TNotebook \
        -background #eff1f5 \
        -bordercolor #c1c4ce \
        -tabmargins {0 2 0 0}
    ttk::style configure TNotebook.Tab \
        -padding {12 6} -focuscolor #1e66f5 \
        -background #e5e7ed \
        -bordercolor #c1c4ce
    ttk::style map TNotebook.Tab \
        -background [list \
            selected #eff1f5 \
            active   #d5d7df] \
        -foreground [list \
            selected #4c4f69 \
            disabled #9ea0af \
            {} #9598a8] \
        -expand [list selected {0 0 0 0}]

    ttk::style configure TPanedwindow -background #c1c4ce
    ttk::style configure Sash -sashthickness 4 -gripcount 0
    ttk::style configure TSeparator -background #c1c4ce

    # ---- scrollbars, scales, progress ----------------------------------
    ttk::style configure TScrollbar \
        -relief flat -borderwidth 0 -arrowsize 12 \
        -troughcolor #eff1f5 \
        -background #cbcdd6 \
        -bordercolor #eff1f5 \
        -arrowcolor #a6a8b6 \
        -darkcolor #cbcdd6 \
        -lightcolor #cbcdd6
    ttk::style map TScrollbar \
        -background [list \
            disabled #eff1f5 \
            pressed  #1e66f5 \
            active   #b8bac5] \
        -darkcolor [list active #b8bac5 pressed #1e66f5] \
        -lightcolor [list active #b8bac5 pressed #1e66f5] \
        -arrowcolor [list disabled #eff1f5]

    ttk::style configure TScale \
        -troughcolor #dbdee4 \
        -background #1e66f5 \
        -bordercolor #c1c4ce \
        -darkcolor #1e66f5 -lightcolor #1e66f5 \
        -troughrelief flat -sliderrelief flat
    ttk::style map TScale \
        -background [list \
            disabled #cbcdd6 \
            active #2761d9] \
        -darkcolor [list active #2761d9] \
        -lightcolor [list active #2761d9]

    ttk::style configure TProgressbar \
        -troughcolor #dbdee4 \
        -background #1e66f5 \
        -bordercolor #dbdee4 \
        -darkcolor #1e66f5 -lightcolor #1e66f5 \
        -troughrelief flat -borderwidth 0 -thickness 8

    # ---- treeview ------------------------------------------------------
    ttk::style configure Treeview \
        -background #e5e7ed \
        -fieldbackground #e5e7ed \
        -foreground #4c4f69 \
        -bordercolor #c1c4ce \
        -borderwidth 0 -rowheight 22
    ttk::style map Treeview \
        -background [list selected #ccd0da] \
        -foreground [list selected #4c4f69 \
                          disabled #9ea0af]
    ttk::style configure Treeview.Heading \
        -padding {6 4} -relief flat \
        -background #d8dae1 \
        -foreground #4c4f69 \
        -bordercolor #c1c4ce
    ttk::style map Treeview.Heading \
        -background [list \
            pressed #c8cad3 \
            active  #ced1d9]
    ttk::style configure Item -focuscolor #1e66f5

    # ---- labels --------------------------------------------------------
    ttk::style configure TLabel -background #eff1f5 -foreground #4c4f69
    ttk::style configure Muted.TLabel -foreground #9598a8
    ttk::style configure Accent.TLabel -foreground #1e66f5
    ttk::style configure Error.TLabel -foreground #d20f39
    ttk::style configure Heading.TLabel -foreground #4c4f69

    ttk::style configure TFrame -background #eff1f5
    ttk::style configure TSizegrip -background #eff1f5
}

# ttk::setTheme, not `ttk::style theme use`. They do the same thing to ttk, but
# only setTheme updates ::ttk::currentTheme -- and that variable is what
# Python's tkinter reports from ttk.Style().theme_use(). Using the lower-level
# call leaves a tkinter host convinced it is still running the `default` theme
# while every widget is drawn in this one.
ttk::setTheme omarchy
ttk::theme::omarchy::repaint
package provide ttk::theme::omarchy $ttk::theme::omarchy::version
