# ttk.tcl -- generated by Omarchy from the active theme's colors.toml.
#
# DO NOT EDIT. This file is rewritten on every `omarchy theme set`.
# Source: themed/ttk.tcl.tpl in tk-omarchy-theme
#
# Registers a ttk theme named "omarchy" built entirely from ttk::style
# statements -- no image elements, so the whole thing is a text substitution
# away from any palette. Sourcing it also repaints the classic (non-ttk)
# widgets, which ttk styling never reaches.
#
# Use it from a Tk app:
#     source $::env(XDG_STATE_HOME)/omarchy/current/theme/ttk.tcl
# or point gitk's "Theme definition file" preference at this path.

package require Tk 8.6-

namespace eval ttk::theme::omarchy {
    variable version 1.0
    variable colors

    # The live Omarchy palette, so an application can colour its own canvases
    # and text tags from the same source: ttk::theme::omarchy::color accent
    array set colors {
        mode        dark
        bg          #1e1e2e
        fg          #cdd6f4
        accent      #89b4fa
        muted       #585b70
        selectbg    #45475a
        selectfg    #cdd6f4

        field       #29293a
        raised      #303042
        hover       #3a3b4e
        pressed     #45465a
        border      #4f5265
        trough      #333446
        disabledfg  #767a91

        red         #f38ba8
        green       #a6e3a1
        yellow      #f9e2af
        blue        #89b4fa
        magenta     #f5c2e7
        cyan        #94e2d5
        orange      #f6b6ab
        bright_fg   #cdd6f4
    }

    proc color {name} {
        variable colors
        if {![info exists colors($name)]} { return "" }
        return $colors($name)
    }

    proc is_dark {} {
        variable colors
        return [expr {$colors(mode) eq "dark"}]
    }

    # tk_setPalette and the option database are the only levers that reach
    # classic widgets (text, listbox, canvas, menu, the Tk dialogs). ttk never
    # consults them, and they never reach a ttk widget -- the two halves are
    # disjoint, so both have to run.
    # --- perceptual colour helpers -------------------------------------
    # Internal. sRGB -> CIELAB, so "are these two colours tellable apart" is a
    # number rather than an opinion. Euclidean distance in RGB is not that
    # number: it rates #549e6a against #459451 as far apart when they are the
    # same green to the eye.
    proc Lab {hex} {
        scan [string range $hex 1 end] %2x%2x%2x r g b
        set lin {}
        foreach c [list $r $g $b] {
            set v [expr {$c / 255.0}]
            lappend lin [expr {$v <= 0.04045 ? $v / 12.92 : pow(($v + 0.055) / 1.055, 2.4)}]
        }
        lassign $lin r g b
        set x [expr {(0.4124 * $r + 0.3576 * $g + 0.1805 * $b) / 0.95047}]
        set y [expr {0.2126 * $r + 0.7152 * $g + 0.0722 * $b}]
        set z [expr {(0.0193 * $r + 0.1192 * $g + 0.9505 * $b) / 1.08883}]
        set f {}
        foreach t [list $x $y $z] {
            lappend f [expr {$t > 0.008856 ? pow($t, 1.0/3.0) : 7.787 * $t + 16.0/116.0}]
        }
        lassign $f fx fy fz
        return [list [expr {116 * $fy - 16}] [expr {500 * ($fx - $fy)}] [expr {200 * ($fy - $fz)}]]
    }

    proc DeltaE {a b} {
        lassign [Lab $a] l1 a1 b1
        lassign [Lab $b] l2 a2 b2
        return [expr {sqrt(pow($l1-$l2,2) + pow($a1-$a2,2) + pow($b1-$b2,2))}]
    }

    proc Luminance {hex} {
        scan [string range $hex 1 end] %2x%2x%2x r g b
        set out 0.0
        foreach c [list $r $g $b] w {0.2126 0.7152 0.0722} {
            set v [expr {$c / 255.0}]
            set v [expr {$v <= 0.03928 ? $v / 12.92 : pow(($v + 0.055) / 1.055, 2.4)}]
            set out [expr {$out + $w * $v}]
        }
        return $out
    }

    # WCAG contrast ratio, 1.0 (identical) to 21.0 (black on white).
    proc Contrast {a b} {
        set la [Luminance $a]
        set lb [Luminance $b]
        if {$la < $lb} { lassign [list $lb $la] la lb }
        return [expr {($la + 0.05) / ($lb + 0.05)}]
    }

    # Pick $n palette colours that are readable on the background and as far
    # apart from each other as this theme allows.
    #
    # Do NOT hand-map meanings onto red/green/yellow/blue: those are terminal
    # palette slots, not a categorical scale, and themes collapse them. On
    # osaka-jade, green/yellow/blue sit within deltaE 21 of one another and
    # blue is byte-identical to accent -- five status rows named that way give
    # you three indistinguishable greens. matte-black and retro-82 are worse:
    # those five names land on deltaE 0.0, one colour wearing five hats.
    #
    # Selection is exhaustive, not greedy. The pool is small by construction
    # (eight or nine candidates), so every combination can be scored and the
    # best min-pairwise-distance taken. Greedy furthest-point was tried first
    # and lost to plain naming on three themes: it is seeded with one colour
    # and never recovers from a bad seed. Because the naming a consumer would
    # have written by hand is itself one of the combinations considered, the
    # result can never be worse than it -- test/hues.sh asserts that.
    #
    # Returns a list of $n hex colours. If the theme cannot supply $n readable
    # ones the contrast floor is relaxed rather than returning a short list.
    proc distinct_hues {n {pool {}}} {
        variable colors
        if {$n <= 0} { return {} }
        # fg and bright_fg are deliberately last: they are text colours, and a
        # theme with high-contrast text will otherwise see them crowd out the
        # actual hues.
        if {$pool eq {}} {
            set pool {accent red green yellow blue magenta cyan orange fg bright_fg}
        }

        set readable {}
        set rest {}
        foreach key $pool {
            set hex [color $key]
            if {![regexp {^#[0-9a-fA-F]{6}$} $hex]} { continue }
            set dup 0
            foreach seen [concat $readable $rest] {
                if {[string equal -nocase $seen $hex]} { set dup 1; break }
            }
            if {$dup} { continue }
            if {[Contrast $hex $colors(bg)] >= 3.0} {
                lappend readable $hex
            } else {
                lappend rest $hex
            }
        }
        while {[llength $readable] < $n && [llength $rest] > 0} {
            lappend readable [lindex $rest 0]
            set rest [lrange $rest 1 end]
        }
        if {[llength $readable] <= $n} { return $readable }

        set best {}
        set best_score -1
        foreach combo [Combinations $readable $n] {
            set score [spread $combo]
            if {$score > $best_score} { set best_score $score; set best $combo }
        }
        return $best
    }

    # Internal. All $n-element subsets of $items, order-insensitive.
    proc Combinations {items n} {
        if {$n == 0} { return [list {}] }
        set out {}
        set len [llength $items]
        for {set i 0} {$i <= $len - $n} {incr i} {
            set head [lindex $items $i]
            foreach tail [Combinations [lrange $items [expr {$i + 1}] end] [expr {$n - 1}]] {
                lappend out [linsert $tail 0 $head]
            }
        }
        return $out
    }

    # WCAG contrast ratio between two colours, 1.0 to 21.0. Public: a consumer
    # choosing text to sit on one of its own colours needs the same number this
    # theme uses internally. 4.5 is the floor for body text, 3.0 for large.
    proc contrast {a b} { return [Contrast $a $b] }

    # Smallest pairwise deltaE in a list of colours. Below about 25 is hard to
    # tell apart; use it to decide whether to fall back to glyphs or weight.
    proc spread {hexes} {
        set worst 1e9
        set n [llength $hexes]
        for {set i 0} {$i < $n} {incr i} {
            for {set j [expr {$i + 1}]} {$j < $n} {incr j} {
                set d [DeltaE [lindex $hexes $i] [lindex $hexes $j]]
                if {$d < $worst} { set worst $d }
            }
        }
        return [expr {$n < 2 ? 0.0 : $worst}]
    }

    # Walk the widget tree applying the field colour to the classic text
    # classes. Only touches widgets whose colour we already own -- a widget the
    # application has coloured itself keeps its colour.
    proc retint {w} {
        variable colors
        switch -- [winfo class $w] {
            Text - Listbox - Entry - Spinbox {
                catch {$w configure -background $colors(field) -foreground $colors(fg)}
                catch {$w configure -insertbackground $colors(fg)}
                catch {$w configure -selectbackground $colors(selectbg) \
                                    -selectforeground $colors(selectfg)}
            }
            Menu {
                catch {$w configure -background $colors(bg) -foreground $colors(fg) \
                                    -activebackground $colors(selectbg) \
                                    -activeforeground $colors(selectfg) \
                                    -selectcolor $colors(accent)}
            }
            Scrollbar - Scale {
                catch {$w configure -background $colors(border) \
                                    -activebackground $colors(disabledfg) \
                                    -troughcolor $colors(bg)}
            }
        }
        foreach child [winfo children $w] { retint $child }
    }

    proc repaint {} {
        variable colors

        tk_setPalette \
            background       $colors(bg) \
            foreground       $colors(fg) \
            activeBackground $colors(hover) \
            activeForeground $colors(fg) \
            disabledForeground $colors(disabledfg) \
            highlightBackground $colors(bg) \
            highlightColor   $colors(accent) \
            insertBackground $colors(fg) \
            selectBackground $colors(selectbg) \
            selectForeground $colors(selectfg) \
            troughColor      $colors(trough)

        # tk_setPalette paints every widget class the same; the text-entry
        # classes want the recessed field colour instead. These need
        # userDefault priority: tk_setPalette's own `*background` entry beats
        # a class-specific `*Text.background` at widgetDefault AND at
        # startupFile -- measured, not assumed -- and userDefault is the first
        # level that takes. See test/option-priority.tcl.
        foreach class {Text Listbox Entry Spinbox} {
            option add *$class.background $colors(field) userDefault
            option add *$class.foreground $colors(fg) userDefault
            option add *$class.selectBackground $colors(selectbg) userDefault
            option add *$class.selectForeground $colors(selectfg) userDefault
            option add *$class.inactiveSelectBackground $colors(trough) userDefault
            option add *$class.highlightBackground $colors(bg) userDefault
            option add *$class.highlightColor $colors(accent) userDefault
        }
        option add *Text.insertBackground $colors(fg) userDefault

        # The classic scrollbar and scale draw their thumb with -background,
        # which tk_setPalette has just set to the window background -- so the
        # thumb becomes invisible against its own trough. ttk::scrollbar is
        # unaffected, but plenty of code still uses the classic one.
        # Thumb and trough must be far apart, not adjacent steps: `raised` and
        # `trough` differ by 2% and rendered as one flat bar. These are the same
        # two values the ttk scrollbar above uses.
        foreach class {Scrollbar Scale} {
            option add *$class.background $colors(border) userDefault
            option add *$class.activeBackground $colors(disabledfg) userDefault
            option add *$class.troughColor $colors(bg) userDefault
            option add *$class.highlightThickness 0 userDefault
            option add *$class.borderWidth 0 userDefault
        }
        option add *Scrollbar.elementBorderWidth 1 userDefault
        option add *Scrollbar.width 12 userDefault
        option add *Scale.sliderRelief flat userDefault
        option add *Menu.activeBackground $colors(selectbg) userDefault
        option add *Menu.activeForeground $colors(selectfg) userDefault
        option add *Menu.selectColor $colors(accent) userDefault
        option add *Menu.borderWidth 1 userDefault
        option add *Menu.relief solid userDefault

        # tk_setPalette reconfigures widgets that already exist, so on a live
        # re-source it has just repainted every text pane with the plain
        # background. The option-database entries above only reach widgets
        # created from here on, so the existing ones need the field colour put
        # back by hand.
        retint .

        # The combobox dropdown is a classic listbox inside a ttk widget.
        option add *TCombobox*Listbox.background $colors(field) userDefault
        option add *TCombobox*Listbox.foreground $colors(fg) userDefault
        option add *TCombobox*Listbox.selectBackground $colors(selectbg) userDefault
        option add *TCombobox*Listbox.selectForeground $colors(selectfg) userDefault
    }
}

# Creating the theme and configuring it are deliberately separate. A running
# application re-sources this file after `omarchy theme set` to pick up the new
# palette, and `theme create` would fail the second time -- while the settings
# block is re-appliable, so the live widgets actually change colour. Doing it
# in one `theme create -settings` call would make re-sourcing a silent no-op.
if {[lsearch -exact [ttk::style theme names] omarchy] < 0} {
    ttk::style theme create omarchy -parent clam
}

ttk::style theme settings omarchy {
    ttk::style configure . \
        -background      #1e1e2e \
        -foreground      #cdd6f4 \
        -troughcolor     #333446 \
        -fieldbackground #29293a \
        -bordercolor     #4f5265 \
        -darkcolor       #303042 \
        -lightcolor      #303042 \
        -focuscolor      #89b4fa \
        -selectbackground #45475a \
        -selectforeground #cdd6f4 \
        -insertcolor     #cdd6f4 \
        -insertwidth     1 \
        -borderwidth     1 \
        -relief          flat \
        -font            TkDefaultFont

    ttk::style map . \
        -background [list disabled #1e1e2e active #3a3b4e] \
        -foreground [list disabled #767a91] \
        -selectbackground [list !focus #333446] \
        -selectforeground [list !focus #cdd6f4]

    # ---- buttons -------------------------------------------------------
    ttk::style configure TButton \
        -anchor center -width -10 -padding {10 5} -relief flat \
        -background #303042
    ttk::style map TButton \
        -background [list \
            disabled #252536 \
            pressed  #45465a \
            active   #3a3b4e] \
        -bordercolor [list focus #89b4fa] \
        -lightcolor [list pressed #45465a] \
        -darkcolor  [list pressed #45465a]

    # An accent button for the one action a dialog actually wants.
    ttk::style configure Accent.TButton \
        -background #89b4fa -foreground #1e1e2e
    ttk::style map Accent.TButton \
        -background [list \
            disabled #303042 \
            pressed  #6e8fc7 \
            active   #93b9f9] \
        -foreground [list disabled #767a91] \
        -lightcolor [list pressed #6e8fc7] \
        -darkcolor  [list pressed #6e8fc7]

    ttk::style configure Toolbutton -anchor center -padding 4 -relief flat \
        -background #1e1e2e
    ttk::style map Toolbutton \
        -background [list \
            selected #45475a \
            pressed  #45465a \
            active   #3a3b4e]

    ttk::style configure TMenubutton \
        -padding {10 5 6 5} -relief flat \
        -background #303042 \
        -arrowcolor #cdd6f4
    ttk::style map TMenubutton \
        -background [list \
            disabled #252536 \
            active   #3a3b4e] \
        -arrowcolor [list disabled #767a91]

    # ---- indicators ----------------------------------------------------
    ttk::style configure TCheckbutton \
        -padding 4 -indicatorbackground #29293a \
        -indicatorforeground #1e1e2e \
        -indicatormargin {0 0 6 0}
    ttk::style map TCheckbutton \
        -background [list active #2c2d3e] \
        -indicatorbackground [list \
            {alternate !disabled} #89b4fa \
            {selected !disabled} #89b4fa \
            {pressed !disabled} #45465a \
            disabled #252536] \
        -indicatorforeground [list \
            {selected !disabled} #1e1e2e \
            disabled #767a91]

    ttk::style configure TRadiobutton \
        -padding 4 -indicatorbackground #29293a \
        -indicatorforeground #1e1e2e \
        -indicatormargin {0 0 6 0}
    ttk::style map TRadiobutton \
        -background [list active #2c2d3e] \
        -indicatorbackground [list \
            {selected !disabled} #89b4fa \
            {pressed !disabled} #45465a \
            disabled #252536] \
        -indicatorforeground [list \
            {selected !disabled} #1e1e2e \
            disabled #767a91]

    # ---- text entry ----------------------------------------------------
    ttk::style configure TEntry \
        -padding {8 5} -insertcolor #cdd6f4 \
        -fieldbackground #29293a \
        -bordercolor #4f5265 \
        -lightcolor #29293a \
        -darkcolor #29293a
    ttk::style map TEntry \
        -fieldbackground [list disabled #1e1e2e readonly #1e1e2e] \
        -bordercolor [list focus #89b4fa invalid #f38ba8] \
        -lightcolor [list focus #89b4fa] \
        -foreground [list disabled #767a91]

    ttk::style configure TSpinbox \
        -padding {8 5 0 5} -arrowsize 12 \
        -arrowcolor #cdd6f4 \
        -fieldbackground #29293a \
        -bordercolor #4f5265 \
        -lightcolor #29293a \
        -darkcolor #29293a
    ttk::style map TSpinbox \
        -fieldbackground [list disabled #1e1e2e readonly #1e1e2e] \
        -bordercolor [list focus #89b4fa] \
        -lightcolor [list focus #89b4fa] \
        -arrowcolor [list disabled #767a91]

    ttk::style configure TCombobox \
        -padding {8 5 0 5} -arrowsize 12 \
        -arrowcolor #cdd6f4 \
        -fieldbackground #29293a \
        -bordercolor #4f5265 \
        -lightcolor #29293a \
        -darkcolor #29293a
    ttk::style map TCombobox \
        -fieldbackground [list \
            disabled #1e1e2e \
            readonly #303042] \
        -bordercolor [list focus #89b4fa] \
        -lightcolor [list focus #89b4fa] \
        -foreground [list disabled #767a91] \
        -arrowcolor [list disabled #767a91]

    # ---- containers ----------------------------------------------------
    ttk::style configure TLabelframe \
        -background #1e1e2e \
        -bordercolor #4f5265 \
        -lightcolor #4f5265 \
        -darkcolor #4f5265 \
        -relief solid -borderwidth 1
    ttk::style configure TLabelframe.Label \
        -background #1e1e2e -foreground #cdd6f4

    ttk::style configure Card.TFrame \
        -background #29293a \
        -bordercolor #4f5265 \
        -relief solid -borderwidth 1

    ttk::style configure TNotebook \
        -background #1e1e2e \
        -bordercolor #4f5265 \
        -tabmargins {0 2 0 0}
    ttk::style configure TNotebook.Tab \
        -padding {12 6} -focuscolor #89b4fa \
        -background #29293a \
        -bordercolor #4f5265
    ttk::style map TNotebook.Tab \
        -background [list \
            selected #1e1e2e \
            active   #3a3b4e] \
        -foreground [list \
            selected #cdd6f4 \
            disabled #767a91 \
            {} #7e839b] \
        -expand [list selected {0 0 0 0}]

    ttk::style configure TPanedwindow -background #4f5265
    ttk::style configure Sash -sashthickness 4 -gripcount 0
    ttk::style configure TSeparator -background #4f5265

    # ---- scrollbars, scales, progress ----------------------------------
    ttk::style configure TScrollbar \
        -relief flat -borderwidth 0 -arrowsize 12 \
        -troughcolor #1e1e2e \
        -background #45465a \
        -bordercolor #1e1e2e \
        -arrowcolor #6d7187 \
        -darkcolor #45465a \
        -lightcolor #45465a
    ttk::style map TScrollbar \
        -background [list \
            disabled #1e1e2e \
            pressed  #89b4fa \
            active   #5a5d71] \
        -darkcolor [list active #5a5d71 pressed #89b4fa] \
        -lightcolor [list active #5a5d71 pressed #89b4fa] \
        -arrowcolor [list disabled #1e1e2e]

    ttk::style configure TScale \
        -troughcolor #333446 \
        -background #89b4fa \
        -bordercolor #4f5265 \
        -darkcolor #89b4fa -lightcolor #89b4fa \
        -troughrelief flat -sliderrelief flat
    ttk::style map TScale \
        -background [list \
            disabled #45465a \
            active #97bbf9] \
        -darkcolor [list active #97bbf9] \
        -lightcolor [list active #97bbf9]

    ttk::style configure TProgressbar \
        -troughcolor #333446 \
        -background #89b4fa \
        -bordercolor #333446 \
        -darkcolor #89b4fa -lightcolor #89b4fa \
        -troughrelief flat -borderwidth 0 -thickness 8

    # ---- treeview ------------------------------------------------------
    ttk::style configure Treeview \
        -background #29293a \
        -fieldbackground #29293a \
        -foreground #cdd6f4 \
        -bordercolor #4f5265 \
        -borderwidth 0 -rowheight 22
    ttk::style map Treeview \
        -background [list selected #45475a] \
        -foreground [list selected #cdd6f4 \
                          disabled #767a91]
    ttk::style configure Treeview.Heading \
        -padding {6 4} -relief flat \
        -background #37384a \
        -foreground #cdd6f4 \
        -bordercolor #4f5265
    ttk::style map Treeview.Heading \
        -background [list \
            pressed #484a5e \
            active  #414356]
    ttk::style configure Item -focuscolor #89b4fa

    # ---- labels --------------------------------------------------------
    ttk::style configure TLabel -background #1e1e2e -foreground #cdd6f4
    ttk::style configure Muted.TLabel -foreground #7e839b
    ttk::style configure Accent.TLabel -foreground #89b4fa
    ttk::style configure Error.TLabel -foreground #f38ba8
    ttk::style configure Heading.TLabel -foreground #cdd6f4

    ttk::style configure TFrame -background #1e1e2e
    ttk::style configure TSizegrip -background #1e1e2e
}

# ttk::setTheme, not `ttk::style theme use`. They do the same thing to ttk, but
# only setTheme updates ::ttk::currentTheme -- and that variable is what
# Python's tkinter reports from ttk.Style().theme_use(). Using the lower-level
# call leaves a tkinter host convinced it is still running the `default` theme
# while every widget is drawn in this one.
ttk::setTheme omarchy
ttk::theme::omarchy::repaint
package provide ttk::theme::omarchy $ttk::theme::omarchy::version
